### ISSUE TITLE
Convert this into telegram bot

### ISSUE THREAD

**Issue by kerokaboom** [sanjit-sinha/PyBypass#1]
Convert this project into a Telegram bot which can be deployed on **_ubuntu server._**

**Comment by missemily22** [comment]
@kerokaboom I take the responsibility for it

**Comment by NesamaniX1** [comment]
> @kerokaboom I take the responsibility for it

🎉

**Comment by kerokaboom** [comment]
No bro not u, sometimes you suck. In your bypass bot you don't allow to add their own drive. You force them to clone/upload content in your drive, that sucks. 

At least leave this project in its on. Keep your monopoly away.

**Comment by missemily22** [comment]
@kerokaboom Bro My Bot was never to public and store things
It was just made to temporarily get gdrive links for easy cloning
If you took an incorrect interpretation it's your fault.

And Last of All ,learn to speak with manners...

**Comment by missemily22** [comment]
@kerokaboom What are you even Bro?
You never understand what the Bot was meant for.
It was not be used as Clone Bot
