### ISSUE TITLE
Add sites

### ISSUE THREAD

**Issue by contusionglory** [sanjit-sinha/PyBypass#15]
If it's possible it will be amazing if you can add the bypass for this sites:
https://i.pkr.pw/
https://try2link.net/
https://ckk.ai/
https://link1s.com/
https://oko.sh/
https://link.usalink.io/
http://link1s.net/

Example Url:
https://i.pkr.pw/fgtwmdk
https://try2link.net/eLarixm
https://ckk.ai/tdazjxb
https://link1s.com/oruywzf
https://oko.sh/hlLibfj
https://link.usalink.io/AupLtfc
http://link1s.net/MiuxnLd

**Comment by askfriends** [comment]
also add support for link-hub.net, it looks like this
https://link-hub.net/5427/mega74

**Comment by sanjit-sinha** [comment]
Currently i don't have any plan to add /update any new sites.
