### ISSUE TITLE
unable to bypass gplinks.

### ISSUE THREAD

**Issue by annihilatorrrr** [sanjit-sinha/PyBypass#2]
**First of all thanks for this excellent bypasser :)**

Error: ``Can not establish a successful connection with the given url.``
PyBypass version: ``1.0.4``
Link: ``https://gplinks.co/sOv2w``

I also tried to run in different servers but None worked.

**Comment by annihilatorrrr** [comment]
Is it removed. ig it was there :')

**Comment by sanjit-sinha** [comment]
It's because Gplinks added cloudfare protection and it cannot be Bypassed using pure requests. Let see if they remove cloudfare protection in future or not.

**Comment by annihilatorrrr** [comment]
> It's because Gplinks added cloudfare protection and it cannot be Bypassed using pure requests. Let see if they remove cloudfare protection in future or not.

hmm i see.
