### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by JAsuran** [sanjit-sinha/PyBypass#3]
http://vearnl.in Bypass working fine 

But tn link and linkbnao got Error.. Not Bypass

**Comment by sanjit-sinha** [comment]
Can you give those links?

**Comment by JAsuran** [comment]
> Can you give those links?

/lb https://linkbnao.com/WrR5CF8

/tn https://tnlink.in/3iWsVo

**Comment by annihilatorrrr** [comment]
> 

https://tnlink.in/3iWsVo give like this ( https included ) both the links works!
tested in t.me/BypassLinksBot using this library.

**Comment by sanjit-sinha** [comment]
I tested those links. And it's working fine from my side.

from PyBypass import bypass

print(bypass("https://linkbnao.com/WrR5CF8"))
print(bypass("https://tnlink.in/3iWsVo"))

**Comment by sanjit-sinha** [comment]
Please use english.

**Comment by JAsuran** [comment]
> Bro Android run panna work aaguma ?

English la kelupa..avarku tamil theriyathu
