### ISSUE TITLE
Add support for more links 

### ISSUE THREAD

**Issue by annihilatorrrr** [sanjit-sinha/PyBypass#6]
Can you please add support for https://terabox.com/ and https://pkin.me/ ?

Here are the example urls:
``https://terabox.com/s/1y_Lns3qOk6BgCuPn8BtErQ``
And
``https://pkin.me/U69JIgs``

**Comment by sanjit-sinha** [comment]
Pkin.me added
I will add terabox later.

**Comment by annihilatorrrr** [comment]
can u make a release of the latest fix on pypi ?

**Comment by sanjit-sinha** [comment]
Yes was doing that only. Was writing changelogs
