### ISSUE TITLE
Streamsb 403 forbidden

### ISSUE THREAD

**Issue by yasirarism** [sanjit-sinha/PyBypass#7]
I'm tes this script to bypass streamsb but always got forbidden. How I can fix it?

```
import PyBypass as bypasser

bypassed_link = bypasser.bypass("https://streamsb.net/d/97vywgdww75r.html")
print(bypassed_link)
```

OUTPUT:
`https://delivery413.akamai-cdn-content.com/hls2/01/07079/0woh067y0ibl_,l,n,.urlset/master.m3u8?t=V7QQenCWN0N5pqsifYVQVSSgyYsYQFKsUsDSz99L76w&s=1667604790&e=10800&f=35399488&srv=sto178&client=141.144.201.241`

**Comment by sanjit-sinha** [comment]
so basically the link you getting is a m3u8 link not a direct download link. That m3u8 link contain various types of video quality (480/720/1080). so you have to write your own script to download video from that m3u8 link and request it with proper headers, payload.

If i get time i will add an example script for how to do that in next update/near future.
